name: Metrics

on:
  # Run once a day
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: repositories
          plugin_languages: yes
          plugin_languages_ignored: ""
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 0
          plugin_languages_sections: most-used
